[package]
name = "rust-slime-simulation"
version = "0.1.0"
edition = "2021"
authors = ["Louis-Muzellec"]
description = "Rust implementation of the slime simulation"

[dependencies]
bevy = "0.8"
bevy_egui = "0.15.0"
bytemuck = "1.10"
rand = "0.8.5"
